### ISSUE TITLE
Library dont work in production 

### ISSUE THREAD

**Issue by logicappsource** [alx610/node-product-catalog-feed#2]
`/home/ubuntu/MNR-api/node_modules/node-product-catalog-feed/lib/product.js:17
  #id;
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/MNR-api/node_modules/node-product-catalog-feed/index.js:1:26)`

**Comment by logicappsource** [comment]
Figured out I was using old node version on ubuntu ec2!
